# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 251e8fad665202023f40d15dd06b8f0f0119d33fff2db7deed41093722c28dd0220d01caa3d0657ef02ca4a2c95bb3df760a07c8dd827b601a7ba3fe64b726b5

test:
  secret_key_base: a5d6ae8724c0c881375394443fca0cbd8a78aba15ec715b387b11483cb10c2693953d9cf14fc2c59c669837c1a0cbe1aa75a28c18e5929c355e93d86ae7420e9

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
